stages:
  create_folders:
    cmd: mkdir -p out
  create_examples:
    cmd: python -m examples_creator
    deps:
      - data/convos.jsonl
      - data/rag_paraphrase_eval.jsonl
      - examples_creator.py
    outs:
      - out/reformulation_examples.pkl
      - out/reformulation_eval.pkl
    params:
      - params.yaml:
        - examples_creator.random_state
        - examples_creator.test_size
  evaluate:
    cmd: PYTHONPATH=../.. python -m evaluate --variant before
    deps:
      - evaluate.py
      - out/reformulation_eval.pkl
      - data/convos.jsonl
      - data/rag_paraphrase_eval.jsonl
    outs:
      - out/eval_results_before.csv
    params:
      - params.yaml:
        - generator_llm.params
  run_optimization:
    cmd: PYTHONPATH=../.. python -m optimize
    deps:
      - optimize.py
      - out/reformulation_examples.pkl
      - out/reformulation_eval.pkl
      - data/convos.jsonl
      - data/rag_paraphrase_eval.jsonl
    outs:
      - out/reform_bot_optimized.json
    params:
      - params.yaml:
        - generator_llm.params
        - reflection_llm.params
        - gepa_config
  evaluate-after:
    cmd: PYTHONPATH=../.. python -m evaluate --variant after
    deps:
      - evaluate.py
      - out/reformulation_eval.pkl
      - data/convos.jsonl
      - data/rag_paraphrase_eval.jsonl
      - out/reform_bot_optimized.json
    outs:
      - out/eval_results_after.csv