examples_creator:
  random_state: 341
  test_size: 0.3

generator_llm:
  kind: clarin
  params:
    model_name: "gemma-4-31b-it"
    temperature: 0.5
    max_tokens: 8000
  untracked_params:
    cache: false
    num_retries: 5

reflection_llm:
  kind: clarin
  params:
    model_name: "or-deepseek-r1-0528"
    temperature: 0.5
    max_tokens: 8000
  untracked_params:
    cache: false
    num_retries: 5

gepa_config:
  max_full_evals: 3
gepa_num_threads: 16

wandb:
  enabled: auto
  project: koda-reformulation
  entity: null
  mode: online
  tags:
    - dvc
    - koda_reformulation
